export interface Country {
  name: string;
  code: string;
  dial_code: string;
  language: string;
}

export const countries: Country[] = [
  { name: "Afghanistan", code: "AF", dial_code: "+93", language: "Pashto" },
  { name: "Albania", code: "AL", dial_code: "+355", language: "Albanian" },
  { name: "Algeria", code: "DZ", dial_code: "+213", language: "Arabic" },
  { name: "American Samoa", code: "AS", dial_code: "+1-684", language: "English" },
  { name: "Andorra", code: "AD", dial_code: "+376", language: "Catalan" },
  { name: "Angola", code: "AO", dial_code: "+244", language: "Portuguese" },
  { name: "Anguilla", code: "AI", dial_code: "+1-264", language: "English" },
  { name: "Antarctica", code: "AQ", dial_code: "+672", language: "English" },
  { name: "Antigua and Barbuda", code: "AG", dial_code: "+1-268", language: "English" },
  { name: "Argentina", code: "AR", dial_code: "+54", language: "Spanish" },
  { name: "Armenia", code: "AM", dial_code: "+374", language: "Armenian" },
  { name: "Aruba", code: "AW", dial_code: "+297", language: "Dutch" },
  { name: "Australia", code: "AU", dial_code: "+61", language: "English" },
  { name: "Austria", code: "AT", dial_code: "+43", language: "German" },
  { name: "Azerbaijan", code: "AZ", dial_code: "+994", language: "Azerbaijani" },
  { name: "Bahamas", code: "BS", dial_code: "+1-242", language: "English" },
  { name: "Bahrain", code: "BH", dial_code: "+973", language: "Arabic" },
  { name: "Bangladesh", code: "BD", dial_code: "+880", language: "Bengali" },
  { name: "Barbados", code: "BB", dial_code: "+1-246", language: "English" },
  { name: "Belarus", code: "BY", dial_code: "+375", language: "Belarusian" },
  { name: "Belgium", code: "BE", dial_code: "+32", language: "Dutch" },
  { name: "Belize", code: "BZ", dial_code: "+501", language: "English" },
  { name: "Benin", code: "BJ", dial_code: "+229", language: "French" },
  { name: "Bermuda", code: "BM", dial_code: "+1-441", language: "English" },
  { name: "Bhutan", code: "BT", dial_code: "+975", language: "Dzongkha" },
  { name: "Bolivia", code: "BO", dial_code: "+591", language: "Spanish" },
  { name: "Bosnia and Herzegovina", code: "BA", dial_code: "+387", language: "Bosnian" },
  { name: "Botswana", code: "BW", dial_code: "+267", language: "English" },
  { name: "Brazil", code: "BR", dial_code: "+55", language: "Portuguese" },
  { name: "British Indian Ocean Territory", code: "IO", dial_code: "+246", language: "English" },
  { name: "British Virgin Islands", code: "VG", dial_code: "+1-284", language: "English" },
  { name: "Brunei", code: "BN", dial_code: "+673", language: "Malay" },
  { name: "Bulgaria", code: "BG", dial_code: "+359", language: "Bulgarian" },
  { name: "Burkina Faso", code: "BF", dial_code: "+226", language: "French" },
  { name: "Burundi", code: "BI", dial_code: "+257", language: "Kirundi" },
  { name: "Cambodia", code: "KH", dial_code: "+855", language: "Khmer" },
  { name: "Cameroon", code: "CM", dial_code: "+237", language: "French" },
  { name: "Canada", code: "CA", dial_code: "+1", language: "English" },
  { name: "Cape Verde", code: "CV", dial_code: "+238", language: "Portuguese" },
  { name: "Cayman Islands", code: "KY", dial_code: "+1-345", language: "English" },
  { name: "Central African Republic", code: "CF", dial_code: "+236", language: "French" },
  { name: "Chad", code: "TD", dial_code: "+235", language: "Arabic" },
  { name: "Chile", code: "CL", dial_code: "+56", language: "Spanish" },
  { name: "China", code: "CN", dial_code: "+86", language: "Chinese" },
  { name: "Christmas Island", code: "CX", dial_code: "+61", language: "English" },
  { name: "Cocos Islands", code: "CC", dial_code: "+61", language: "English" },
  { name: "Colombia", code: "CO", dial_code: "+57", language: "Spanish" },
  { name: "Comoros", code: "KM", dial_code: "+269", language: "Comorian" },
  { name: "Cook Islands", code: "CK", dial_code: "+682", language: "English" },
  { name: "Costa Rica", code: "CR", dial_code: "+506", language: "Spanish" },
  { name: "Croatia", code: "HR", dial_code: "+385", language: "Croatian" },
  { name: "Cuba", code: "CU", dial_code: "+53", language: "Spanish" },
  { name: "Curacao", code: "CW", dial_code: "+599", language: "Dutch" },
  { name: "Cyprus", code: "CY", dial_code: "+357", language: "Greek" },
  { name: "Czech Republic", code: "CZ", dial_code: "+420", language: "Czech" },
  { name: "Democratic Republic of the Congo", code: "CD", dial_code: "+243", language: "French" },
  { name: "Denmark", code: "DK", dial_code: "+45", language: "Danish" },
  { name: "Djibouti", code: "DJ", dial_code: "+253", language: "French" },
  { name: "Dominica", code: "DM", dial_code: "+1-767", language: "English" },
  { name: "Dominican Republic", code: "DO", dial_code: "+1-809", language: "Spanish" },
  { name: "East Timor", code: "TL", dial_code: "+670", language: "Tetum" },
  { name: "Ecuador", code: "EC", dial_code: "+593", language: "Spanish" },
  { name: "Egypt", code: "EG", dial_code: "+20", language: "Arabic" },
  { name: "El Salvador", code: "SV", dial_code: "+503", language: "Spanish" },
  { name: "Equatorial Guinea", code: "GQ", dial_code: "+240", language: "Spanish" },
  { name: "Eritrea", code: "ER", dial_code: "+291", language: "Tigrinya" },
  { name: "Estonia", code: "EE", dial_code: "+372", language: "Estonian" },
  { name: "Ethiopia", code: "ET", dial_code: "+251", language: "Amharic" },
  { name: "Falkland Islands", code: "FK", dial_code: "+500", language: "English" },
  { name: "Faroe Islands", code: "FO", dial_code: "+298", language: "Faroese" },
  { name: "Fiji", code: "FJ", dial_code: "+679", language: "English" },
  { name: "Finland", code: "FI", dial_code: "+358", language: "Finnish" },
  { name: "France", code: "FR", dial_code: "+33", language: "French" },
  { name: "French Polynesia", code: "PF", dial_code: "+689", language: "French" },
  { name: "Gabon", code: "GA", dial_code: "+241", language: "French" },
  { name: "Gambia", code: "GM", dial_code: "+220", language: "English" },
  { name: "Georgia", code: "GE", dial_code: "+995", language: "Georgian" },
  { name: "Germany", code: "DE", dial_code: "+49", language: "German" },
  { name: "Ghana", code: "GH", dial_code: "+233", language: "English" },
  { name: "Gibraltar", code: "GI", dial_code: "+350", language: "English" },
  { name: "Greece", code: "GR", dial_code: "+30", language: "Greek" },
  { name: "Greenland", code: "GL", dial_code: "+299", language: "Greenlandic" },
  { name: "Grenada", code: "GD", dial_code: "+1-473", language: "English" },
  { name: "Guam", code: "GU", dial_code: "+1-671", language: "English" },
  { name: "Guatemala", code: "GT", dial_code: "+502", language: "Spanish" },
  { name: "Guernsey", code: "GG", dial_code: "+44-1481", language: "English" },
  { name: "Guinea", code: "GN", dial_code: "+224", language: "French" },
  { name: "Guinea-Bissau", code: "GW", dial_code: "+245", language: "Portuguese" },
  { name: "Guyana", code: "GY", dial_code: "+592", language: "English" },
  { name: "Haiti", code: "HT", dial_code: "+509", language: "French" },
  { name: "Honduras", code: "HN", dial_code: "+504", language: "Spanish" },
  { name: "Hong Kong", code: "HK", dial_code: "+852", language: "Chinese" },
  { name: "Hungary", code: "HU", dial_code: "+36", language: "Hungarian" },
  { name: "Iceland", code: "IS", dial_code: "+354", language: "Icelandic" },
  { name: "India", code: "IN", dial_code: "+91", language: "Hindi" },
  { name: "Indonesia", code: "ID", dial_code: "+62", language: "Indonesian" },
  { name: "Iran", code: "IR", dial_code: "+98", language: "Persian" },
  { name: "Iraq", code: "IQ", dial_code: "+964", language: "Arabic" },
  { name: "Ireland", code: "IE", dial_code: "+353", language: "English" },
  { name: "Isle of Man", code: "IM", dial_code: "+44-1624", language: "English" },
  { name: "Israel", code: "IL", dial_code: "+972", language: "Hebrew" },
  { name: "Italy", code: "IT", dial_code: "+39", language: "Italian" },
  { name: "Ivory Coast", code: "CI", dial_code: "+225", language: "French" },
  { name: "Jamaica", code: "JM", dial_code: "+1-876", language: "English" },
  { name: "Japan", code: "JP", dial_code: "+81", language: "Japanese" },
  { name: "Jersey", code: "JE", dial_code: "+44-1534", language: "English" },
  { name: "Jordan", code: "JO", dial_code: "+962", language: "Arabic" },
  { name: "Kazakhstan", code: "KZ", dial_code: "+7", language: "Kazakh" },
  { name: "Kenya", code: "KE", dial_code: "+254", language: "Swahili" },
  { name: "Kiribati", code: "KI", dial_code: "+686", language: "English" },
  { name: "Kosovo", code: "XK", dial_code: "+383", language: "Albanian" },
  { name: "Kuwait", code: "KW", dial_code: "+965", language: "Arabic" },
  { name: "Kyrgyzstan", code: "KG", dial_code: "+996", language: "Kyrgyz" },
  { name: "Laos", code: "LA", dial_code: "+856", language: "Lao" },
  { name: "Latvia", code: "LV", dial_code: "+371", language: "Latvian" },
  { name: "Lebanon", code: "LB", dial_code: "+961", language: "Arabic" },
  { name: "Lesotho", code: "LS", dial_code: "+266", language: "Sesotho" },
  { name: "Liberia", code: "LR", dial_code: "+231", language: "English" },
  { name: "Libya", code: "LY", dial_code: "+218", language: "Arabic" },
  { name: "Liechtenstein", code: "LI", dial_code: "+423", language: "German" },
  { name: "Lithuania", code: "LT", dial_code: "+370", language: "Lithuanian" },
  { name: "Luxembourg", code: "LU", dial_code: "+352", language: "Luxembourgish" },
  { name: "Macau", code: "MO", dial_code: "+853", language: "Chinese" },
  { name: "Macedonia", code: "MK", dial_code: "+389", language: "Macedonian" },
  { name: "Madagascar", code: "MG", dial_code: "+261", language: "Malagasy" },
  { name: "Malawi", code: "MW", dial_code: "+265", language: "English" },
  { name: "Malaysia", code: "MY", dial_code: "+60", language: "Malay" },
  { name: "Maldives", code: "MV", dial_code: "+960", language: "Divehi" },
  { name: "Mali", code: "ML", dial_code: "+223", language: "French" },
  { name: "Malta", code: "MT", dial_code: "+356", language: "Maltese" },
  { name: "Marshall Islands", code: "MH", dial_code: "+692", language: "English" },
  { name: "Mauritania", code: "MR", dial_code: "+222", language: "Arabic" },
  { name: "Mauritius", code: "MU", dial_code: "+230", language: "English" },
  { name: "Mayotte", code: "YT", dial_code: "+262", language: "French" },
  { name: "Mexico", code: "MX", dial_code: "+52", language: "Spanish" },
  { name: "Micronesia", code: "FM", dial_code: "+691", language: "English" },
  { name: "Moldova", code: "MD", dial_code: "+373", language: "Romanian" },
  { name: "Monaco", code: "MC", dial_code: "+377", language: "French" },
  { name: "Mongolia", code: "MN", dial_code: "+976", language: "Mongolian" },
  { name: "Montenegro", code: "ME", dial_code: "+382", language: "Montenegrin" },
  { name: "Montserrat", code: "MS", dial_code: "+1-664", language: "English" },
  { name: "Morocco", code: "MA", dial_code: "+212", language: "Arabic" },
  { name: "Mozambique", code: "MZ", dial_code: "+258", language: "Portuguese" },
  { name: "Myanmar", code: "MM", dial_code: "+95", language: "Burmese" },
  { name: "Namibia", code: "NA", dial_code: "+264", language: "English" },
  { name: "Nauru", code: "NR", dial_code: "+674", language: "English" },
  { name: "Nepal", code: "NP", dial_code: "+977", language: "Nepali" },
  { name: "Netherlands", code: "NL", dial_code: "+31", language: "Dutch" },
  { name: "New Caledonia", code: "NC", dial_code: "+687", language: "French" },
  { name: "New Zealand", code: "NZ", dial_code: "+64", language: "English" },
  { name: "Nicaragua", code: "NI", dial_code: "+505", language: "Spanish" },
  { name: "Niger", code: "NE", dial_code: "+227", language: "French" },
  { name: "Nigeria", code: "NG", dial_code: "+234", language: "English" },
  { name: "Niue", code: "NU", dial_code: "+683", language: "English" },
  { name: "North Korea", code: "KP", dial_code: "+850", language: "Korean" },
  { name: "Northern Mariana Islands", code: "MP", dial_code: "+1-670", language: "English" },
  { name: "Norway", code: "NO", dial_code: "+47", language: "Norwegian" },
  { name: "Oman", code: "OM", dial_code: "+968", language: "Arabic" },
  { name: "Pakistan", code: "PK", dial_code: "+92", language: "Urdu" },
  { name: "Palau", code: "PW", dial_code: "+680", language: "English" },
  { name: "Palestine", code: "PS", dial_code: "+970", language: "Arabic" },
  { name: "Panama", code: "PA", dial_code: "+507", language: "Spanish" },
  { name: "Papua New Guinea", code: "PG", dial_code: "+675", language: "English" },
  { name: "Paraguay", code: "PY", dial_code: "+595", language: "Spanish" },
  { name: "Peru", code: "PE", dial_code: "+51", language: "Spanish" },
  { name: "Philippines", code: "PH", dial_code: "+63", language: "Filipino" },
  { name: "Pitcairn", code: "PN", dial_code: "+870", language: "English" },
  { name: "Poland", code: "PL", dial_code: "+48", language: "Polish" },
  { name: "Portugal", code: "PT", dial_code: "+351", language: "Portuguese" },
  { name: "Puerto Rico", code: "PR", dial_code: "+1-787", language: "Spanish" },
  { name: "Qatar", code: "QA", dial_code: "+974", language: "Arabic" },
  { name: "Republic of the Congo", code: "CG", dial_code: "+242", language: "French" },
  { name: "Romania", code: "RO", dial_code: "+40", language: "Romanian" },
  { name: "Russia", code: "RU", dial_code: "+7", language: "Russian" },
  { name: "Rwanda", code: "RW", dial_code: "+250", language: "Kinyarwanda" },
  { name: "Saint Barthelemy", code: "BL", dial_code: "+590", language: "French" },
  { name: "Saint Helena", code: "SH", dial_code: "+290", language: "English" },
  { name: "Saint Kitts and Nevis", code: "KN", dial_code: "+1-869", language: "English" },
  { name: "Saint Lucia", code: "LC", dial_code: "+1-758", language: "English" },
  { name: "Saint Martin", code: "MF", dial_code: "+590", language: "French" },
  { name: "Saint Pierre and Miquelon", code: "PM", dial_code: "+508", language: "French" },
  { name: "Saint Vincent and the Grenadines", code: "VC", dial_code: "+1-784", language: "English" },
  { name: "Samoa", code: "WS", dial_code: "+685", language: "Samoan" },
  { name: "San Marino", code: "SM", dial_code: "+378", language: "Italian" },
  { name: "Sao Tome and Principe", code: "ST", dial_code: "+239", language: "Portuguese" },
  { name: "Saudi Arabia", code: "SA", dial_code: "+966", language: "Arabic" },
  { name: "Senegal", code: "SN", dial_code: "+221", language: "French" },
  { name: "Serbia", code: "RS", dial_code: "+381", language: "Serbian" },
  { name: "Seychelles", code: "SC", dial_code: "+248", language: "French" },
  { name: "Sierra Leone", code: "SL", dial_code: "+232", language: "English" },
  { name: "Singapore", code: "SG", dial_code: "+65", language: "English" },
  { name: "Sint Maarten", code: "SX", dial_code: "+1-721", language: "English" },
  { name: "Slovakia", code: "SK", dial_code: "+421", language: "Slovak" },
  { name: "Slovenia", code: "SI", dial_code: "+386", language: "Slovenian" },
  { name: "Solomon Islands", code: "SB", dial_code: "+677", language: "English" },
  { name: "Somalia", code: "SO", dial_code: "+252", language: "Somali" },
  { name: "South Africa", code: "ZA", dial_code: "+27", language: "English" },
  { name: "South Korea", code: "KR", dial_code: "+82", language: "Korean" },
  { name: "South Sudan", code: "SS", dial_code: "+211", language: "English" },
  { name: "Spain", code: "ES", dial_code: "+34", language: "Spanish" },
  { name: "Sri Lanka", code: "LK", dial_code: "+94", language: "Sinhala" },
  { name: "Sudan", code: "SD", dial_code: "+249", language: "Arabic" },
  { name: "Suriname", code: "SR", dial_code: "+597", language: "Dutch" },
  { name: "Svalbard and Jan Mayen", code: "SJ", dial_code: "+47", language: "Norwegian" },
  { name: "Swaziland", code: "SZ", dial_code: "+268", language: "English" },
  { name: "Sweden", code: "SE", dial_code: "+46", language: "Swedish" },
  { name: "Switzerland", code: "CH", dial_code: "+41", language: "German" },
  { name: "Syria", code: "SY", dial_code: "+963", language: "Arabic" },
  { name: "Taiwan", code: "TW", dial_code: "+886", language: "Chinese" },
  { name: "Tajikistan", code: "TJ", dial_code: "+992", language: "Tajik" },
  { name: "Tanzania", code: "TZ", dial_code: "+255", language: "Swahili" },
  { name: "Thailand", code: "TH", dial_code: "+66", language: "Thai" },
  { name: "Togo", code: "TG", dial_code: "+228", language: "French" },
  { name: "Tokelau", code: "TK", dial_code: "+690", language: "English" },
  { name: "Tonga", code: "TO", dial_code: "+676", language: "Tongan" },
  { name: "Trinidad and Tobago", code: "TT", dial_code: "+1-868", language: "English" },
  { name: "Tunisia", code: "TN", dial_code: "+216", language: "Arabic" },
  { name: "Turkey", code: "TR", dial_code: "+90", language: "Turkish" },
  { name: "Turkmenistan", code: "TM", dial_code: "+993", language: "Turkmen" },
  { name: "Turks and Caicos Islands", code: "TC", dial_code: "+1-649", language: "English" },
  { name: "Tuvalu", code: "TV", dial_code: "+688", language: "English" },
  { name: "U.S. Virgin Islands", code: "VI", dial_code: "+1-340", language: "English" },
  { name: "Uganda", code: "UG", dial_code: "+256", language: "English" },
  { name: "Ukraine", code: "UA", dial_code: "+380", language: "Ukrainian" },
  { name: "United Arab Emirates", code: "AE", dial_code: "+971", language: "Arabic" },
  { name: "United Kingdom", code: "GB", dial_code: "+44", language: "English" },
  { name: "United States", code: "US", dial_code: "+1", language: "English" },
  { name: "Uruguay", code: "UY", dial_code: "+598", language: "Spanish" },
  { name: "Uzbekistan", code: "UZ", dial_code: "+998", language: "Uzbek" },
  { name: "Vanuatu", code: "VU", dial_code: "+678", language: "Bislama" },
  { name: "Vatican", code: "VA", dial_code: "+379", language: "Italian" },
  { name: "Venezuela", code: "VE", dial_code: "+58", language: "Spanish" },
  { name: "Vietnam", code: "VN", dial_code: "+84", language: "Vietnamese" },
  { name: "Wallis and Futuna", code: "WF", dial_code: "+681", language: "French" },
  { name: "Western Sahara", code: "EH", dial_code: "+212", language: "Arabic" },
  { name: "Yemen", code: "YE", dial_code: "+967", language: "Arabic" },
  { name: "Zambia", code: "ZM", dial_code: "+260", language: "English" },
  { name: "Zimbabwe", code: "ZW", dial_code: "+263", language: "English" }
];